import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Header from "../(components)/header/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Header/>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
