import type { Metadata } from "next";
import "./globals.css";
import Header from "../(components)/header/page";
import { GoogleAnalytics } from '@next/third-parties/google';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Header/>
        <main>{children}</main>
        <footer></footer>
        <GoogleAnalytics gaId="G-XYZ"/>
      </body>
    </html>
  );
}
